\i sql/include/test_setup.sql

BEGIN;

SET ROLE TO sql_saga_unprivileged_user;
SET client_min_messages TO NOTICE;

\echo '----------------------------------------------------------------------------'
\echo 'Test: Synchronization with an authoritative range column'
\echo '----------------------------------------------------------------------------'

\echo '--- 1. Test DATE range with auto-detected synchronized bounds ---'
SAVEPOINT test_1;
CREATE TABLE sync_range_default (id int, valid_range daterange, valid_from date, valid_to date, valid_until date);
SELECT sql_saga.add_era('sync_range_default', 'valid_range');
\d sync_range_default
-- 1a. INSERT with from,until, range is auto-populated
INSERT INTO sync_range_default (id, valid_from, valid_until) VALUES (1, '2024-01-01', '2025-01-01');
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_range_default WHERE id = 1;
-- 1b. INSERT with from,to, range is auto-populated
INSERT INTO sync_range_default (id, valid_from, valid_until) VALUES (2, '2025-01-01', '2026-01-01');
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_range_default WHERE id = 2;
-- 1c. INSERT with range, bounds are auto-populated
INSERT INTO sync_range_default (id, valid_range) VALUES (3, '[2024-02-01, 2025-02-01)');
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_range_default WHERE id = 3;
-- 1d. UPDATE from,until, range is auto-updated
UPDATE sync_range_default SET valid_from = '2026-01-01', valid_until = '2027-01-01' WHERE id = 1;
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_range_default WHERE id = 1;
-- 1e. UPDATE from,to, range is auto-updated
UPDATE sync_range_default SET valid_from = '2027-01-01', valid_to = '2027-12-31' WHERE id = 1;
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_range_default WHERE id = 1;
-- 1e. UPDATE range, bounds are auto-updated
UPDATE sync_range_default SET valid_range = '[2028-01-01, 2029-01-01)' WHERE id = 1;
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_range_default WHERE id = 1;
ROLLBACK TO SAVEPOINT test_1;

\echo '--- 2. Test disabling synchronization ---'
SAVEPOINT test_2;
CREATE TABLE sync_range_disabled (id int, valid_range daterange, valid_from date, valid_until date);
-- Note: synchronize_columns is set to false, so no trigger is created.
SELECT sql_saga.add_era('sync_range_disabled', 'valid_range', synchronize_columns := false);
\d sync_range_disabled
-- This will succeed with inconsistent data, proving the trigger was not created.
INSERT INTO sync_range_disabled (id, valid_range, valid_from, valid_until) VALUES (1,'[2099-01-01, 2099-12-31)', '2024-01-01', '2025-01-01');
SELECT id, valid_range, valid_from, valid_until FROM sync_range_disabled;
ROLLBACK TO SAVEPOINT test_2;

\echo '--- 3. Test with a custom column name and INT4RANGE (a discrete type) ---'
SAVEPOINT test_3;
CREATE TABLE sync_range_custom (id int, start_num int, until_num int, num_range int4range, to_num int);
SELECT sql_saga.add_era('sync_range_custom', 'num_range', valid_from_column_name := 'start_num', valid_until_column_name := 'until_num', valid_to_column_name := 'to_num');
\d sync_range_custom
INSERT INTO sync_range_custom (id, num_range) VALUES (1, '[100, 200)');
SELECT id, start_num, until_num, num_range, to_num FROM sync_range_custom;
ROLLBACK TO SAVEPOINT test_3;

\echo '--- 4. Test trigger consistency: inconsistent data on INSERT ---'
SAVEPOINT test_4;
-- The trigger now checks for consistency and raises an error on mismatch.
CREATE TABLE sync_range_error (id int, valid_range daterange, valid_from date, valid_to date, valid_until date);
-- Auto-detects all columns for synchronization
SELECT sql_saga.add_era('sync_range_error', 'valid_range');
-- This should fail due to inconsistency between valid_to and valid.
DO $$
BEGIN
    INSERT INTO sync_range_error (id, valid_range, valid_from, valid_to) VALUES (1, '[2024-01-01, 2025-01-01)', '2024-01-01', '2099-12-31');
EXCEPTION WHEN others THEN
    RAISE NOTICE 'Caught expected error: %', SQLERRM;
END;
$$;
SELECT * FROM sync_range_error; -- should be empty
ROLLBACK TO SAVEPOINT test_4;


\echo '--- 5. Test inclusive-upper bound range is handled ---'
SAVEPOINT test_5;
CREATE TABLE sync_range_bounds (id int, valid_range daterange, valid_from date, valid_until date);
SELECT sql_saga.add_era('sync_range_bounds', 'valid_range');
-- The trigger will extract the bounds from the input range and re-create a
-- canonical '[)' range, so this will be corrected, not rejected.
INSERT INTO sync_range_bounds (id, valid_range) VALUES (1, daterange('2024-01-01', '2024-12-31', '[]'));
SELECT * FROM sync_range_bounds;
ROLLBACK TO SAVEPOINT test_5;

\echo '--- 6. Test edge case: generated column is skipped ---'
SAVEPOINT test_6;
CREATE TABLE sync_range_generated (
    id          int GENERATED BY DEFAULT AS IDENTITY,
    valid_range daterange NOT NULL,
    
    valid_from  date GENERATED ALWAYS AS (
                    lower(valid_range)
                ) STORED,
                
    valid_to date GENERATED ALWAYS AS (
                    CASE 
                        WHEN upper_inf(valid_range) THEN 'infinity'::date
                        WHEN upper_inc(valid_range)  THEN upper(valid_range)      -- [a,b] → b
                        ELSE upper(valid_range) - 1                               -- [a,b) → b-1
                    END
                ) STORED,

    valid_until date GENERATED ALWAYS AS (
                    CASE 
                        WHEN upper_inf(valid_range) THEN 'infinity'::date
                        WHEN upper_inc(valid_range)  THEN upper(valid_range) + 1  -- [a,b] → b+1
                        ELSE upper(valid_range)                                   -- [a,b) → b
                    END
                ) STORED,
    PRIMARY KEY (id, valid_range)
);
SELECT sql_saga.add_era('sync_range_generated', 'valid_range');
\d sync_range_generated
-- This will succeed, proving no trigger was created.
INSERT INTO sync_range_generated (id, valid_range) VALUES (1, '[2024-01-01,2025-01-01)');
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_range_generated;
ROLLBACK TO SAVEPOINT test_6;

\echo '--- 7. Test interaction between all synchronization columns ---'
SAVEPOINT test_7;
CREATE TABLE sync_both (id int, valid_range daterange, valid_from date, valid_to date, valid_until date);
\d sync_both
SAVEPOINT test_7_table_created;

\echo '--- 7a. sync (defaults on, but not used) ---'
SELECT sql_saga.add_era('sync_both', 'valid_range', synchronize_columns => true);
-- INSERT with range, other columns are auto-populated
INSERT INTO sync_both (id, valid_range) VALUES (1, '[2024-01-01, 2025-01-01)');
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=1;
-- INSERT with valid_to, other columns are auto-populated
INSERT INTO sync_both (id, valid_from, valid_to) VALUES (2, '2026-01-01', '2026-12-31');
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=2;
-- INSERT with valid_until, other columns are auto-populated
INSERT INTO sync_both (id, valid_from, valid_until) VALUES (3, '2028-01-01', '2029-01-01');
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=3;
ROLLBACK TO SAVEPOINT test_7_table_created;

\echo '--- 7b. sync_no_defaults ---'
SELECT sql_saga.add_era('sync_both', 'valid_range', synchronize_columns => true, add_defaults => false);

\echo '--- INSERTs ---'
DO $$ BEGIN INSERT INTO sync_both (id, valid_from, valid_until) VALUES (10, '2024-01-01', NULL); EXCEPTION WHEN others THEN RAISE NOTICE 'Caught expected error: %', SQLERRM; END; $$;
DO $$ BEGIN INSERT INTO sync_both (id, valid_from, valid_to) VALUES (11, '2024-01-01', NULL); EXCEPTION WHEN others THEN RAISE NOTICE 'Caught expected error: %', SQLERRM; END; $$;
DO $$ BEGIN INSERT INTO sync_both (id, valid_from) VALUES (12, '2024-01-01'); EXCEPTION WHEN others THEN RAISE NOTICE 'Caught expected error: %', SQLERRM; END; $$;
DO $$ BEGIN INSERT INTO sync_both (id, valid_range) VALUES (13, NULL); EXCEPTION WHEN others THEN RAISE NOTICE 'Caught expected error: %', SQLERRM; END; $$;
INSERT INTO sync_both (id, valid_range) VALUES (14, '[2024-01-01, infinity)');
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=14;
DO $$ BEGIN INSERT INTO sync_both (id, valid_range) VALUES (15, '[2024-01-01,)'); EXCEPTION WHEN others THEN RAISE NOTICE 'Caught expected error: %', SQLERRM; END; $$;
\echo '--- UPDATEs ---'
INSERT INTO sync_both (id, valid_from, valid_until) VALUES (16, '2024-01-01', '2025-01-01');
DO $$ BEGIN UPDATE sync_both SET valid_until = NULL WHERE id = 16; EXCEPTION WHEN others THEN RAISE NOTICE 'Caught expected error: %', SQLERRM; END; $$;
DO $$ BEGIN UPDATE sync_both SET valid_to = NULL WHERE id = 16; EXCEPTION WHEN others THEN RAISE NOTICE 'Caught expected error: %', SQLERRM; END; $$;
UPDATE sync_both SET valid_range = '[2026-01-01, infinity)' WHERE id = 16;
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=16;
DO $$ BEGIN UPDATE sync_both SET valid_range = '[2027-01-01,)' WHERE id = 16; EXCEPTION WHEN others THEN RAISE NOTICE 'Caught expected error: %', SQLERRM; END; $$;
ROLLBACK TO SAVEPOINT test_7_table_created;

\echo '--- 7c. sync_with_defaults ---'
SELECT sql_saga.add_era('sync_both', 'valid_range', synchronize_columns => true, add_defaults => true);

\echo '--- INSERTs ---'
DO $$ BEGIN INSERT INTO sync_both (id, valid_from) VALUES (20, NULL); EXCEPTION WHEN others THEN RAISE NOTICE 'Caught expected error: %', SQLERRM; END; $$;
INSERT INTO sync_both (id, valid_from, valid_until) VALUES (21, '2024-01-01', NULL);
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=21;
INSERT INTO sync_both (id, valid_from, valid_to) VALUES (22, '2025-01-01', NULL);
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=22;
DO $$ BEGIN INSERT INTO sync_both (id, valid_range) VALUES (23, NULL); EXCEPTION WHEN others THEN RAISE NOTICE 'Caught expected error: %', SQLERRM; END; $$;
INSERT INTO sync_both (id, valid_range) VALUES (24, '[2026-01-01, infinity)');
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=24;
INSERT INTO sync_both (id, valid_range) VALUES (25, '[2027-01-01,)');
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=25;
\echo '--- UPDATEs ---'
INSERT INTO sync_both (id, valid_from, valid_until) VALUES (26, '2024-01-01', '2025-01-01');
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=26;
SAVEPOINT test_7_sync_both_setup;
DO $$ BEGIN UPDATE sync_both SET valid_from = NULL WHERE id = 26; EXCEPTION WHEN others THEN RAISE NOTICE 'Caught expected error: %', SQLERRM; END; $$;
ROLLBACK TO SAVEPOINT test_7_sync_both_setup;
UPDATE sync_both SET valid_until = NULL WHERE id = 26;
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=26;
ROLLBACK TO SAVEPOINT test_7_sync_both_setup;
UPDATE sync_both SET valid_from = '2025-01-01', valid_to = NULL WHERE id = 26;
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=26;
ROLLBACK TO SAVEPOINT test_7_sync_both_setup;
UPDATE sync_both SET valid_range = '[2026-01-01, infinity)' WHERE id = 26;
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=26;
ROLLBACK TO SAVEPOINT test_7_sync_both_setup;
UPDATE sync_both SET valid_range = '[2027-01-01,)' WHERE id = 26;
SELECT id, valid_range, valid_from, valid_to, valid_until FROM sync_both WHERE id=26;
ROLLBACK TO SAVEPOINT test_7_table_created;

-- 7d. INSERT with inconsistent multiple representations should fail.
\echo '--- 7d. Test inconsistent multiple inputs ---'
SELECT sql_saga.add_era('sync_both', 'valid_range', synchronize_columns => true, add_defaults => true);
DO $$
BEGIN
    INSERT INTO sync_both (id, valid_range, valid_from, valid_to, valid_until) VALUES (5, '[2030-01-01, 2031-01-01)', '2030-02-01', '2032-12-31', '2033-12-31');
EXCEPTION WHEN others THEN
    RAISE NOTICE 'Caught expected error: %', SQLERRM;
END;
$$;
SELECT * FROM sync_both WHERE id=5; -- should be empty

ROLLBACK TO SAVEPOINT test_7_table_created;

-- 7e. UPDATE with INCONSISTENT multiple representations
\echo '--- 7e. Test inconsistent update ---'
SELECT sql_saga.add_era('sync_both', 'valid_range', synchronize_columns => true, add_defaults => true);
INSERT INTO sync_both (id, valid_range) VALUES (27, '[2024-01-01, infinity)');
DO $$
BEGIN
    UPDATE sync_both SET valid_to = '2025-12-31', valid_range = '[2099-01-01, 2100-01-01)' WHERE id = 27;
EXCEPTION WHEN others THEN
    RAISE NOTICE 'Caught expected error: %', SQLERRM;
END;
$$;

SELECT * FROM sync_both WHERE id=27; -- should be inserted value (no UPDATE)

ROLLBACK TO SAVEPOINT test_7;

\echo '--- 8. Test continuous types disable valid_to sync ---'
SAVEPOINT test_8a;
\echo '--- 8a. timestamptz ---'
CREATE TABLE sync_continuous_tstz (id int, valid_range tstzrange, valid_from timestamptz, valid_to timestamptz, valid_until timestamptz);
SELECT sql_saga.add_era('sync_continuous_tstz', 'valid_range');
\d+ sync_continuous_tstz
INSERT INTO sync_continuous_tstz (id, valid_from, valid_to, valid_until) VALUES (1, '2024-01-01', '2099-12-31', '2025-01-01');
SELECT * FROM sync_continuous_tstz;
ROLLBACK TO SAVEPOINT test_8a;

SAVEPOINT test_8b;
\echo '--- 8b. timestamp ---'
CREATE TABLE sync_continuous_ts (id int, valid_range tsrange, valid_from timestamp, valid_to timestamp, valid_until timestamp);
SELECT sql_saga.add_era('sync_continuous_ts', 'valid_range');
\d+ sync_continuous_ts
INSERT INTO sync_continuous_ts (id, valid_from, valid_to, valid_until) VALUES (1, '2024-01-01', '2099-12-31', '2025-01-01');
SELECT * FROM sync_continuous_ts;
ROLLBACK TO SAVEPOINT test_8b;

SAVEPOINT test_8c;
\echo '--- 8c. numeric ---'
CREATE TABLE sync_continuous_numeric (id int, valid_range numrange, valid_from numeric, valid_to numeric, valid_until numeric);
SELECT sql_saga.add_era('sync_continuous_numeric', 'valid_range');
\d+ sync_continuous_numeric
INSERT INTO sync_continuous_numeric (id, valid_from, valid_to, valid_until) VALUES (1, 100.5, 999.9, 200.5);
SELECT * FROM sync_continuous_numeric;
ROLLBACK TO SAVEPOINT test_8c;

ROLLBACK;

\i sql/include/test_teardown.sql
