\i sql/include/test_setup.sql

-- This test file reproduces two distinct regressions in `temporal_merge`.
-- Each regression is tested in its own savepoint for isolation.

\set ECHO all

BEGIN;

CREATE SCHEMA saga_repro;

-- Base table definitions used by both scenarios
CREATE TABLE saga_repro.target_units_template (
    unit_ident text NOT NULL,
    name text,
    valid_range daterange NOT NULL,
    valid_from date NOT NULL,
    valid_to date,
    valid_until date
);
CREATE TABLE saga_repro.source_units_template (
    row_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_seq int,
    unit_ident text,
    name text,
    sector text,
    valid_from date,
    valid_to date,
    merge_status jsonb,
    errors jsonb
);

GRANT USAGE ON SCHEMA saga_repro TO sql_saga_unprivileged_user;

--------------------------------------------------------------------------------
-- SCENARIO 1: Ordering Dependency Regression
--
-- This script demonstrates a regression where `temporal_merge` fails if its
-- source data contains complex overlapping temporal segments that are not
-- pre-sorted chronologically.
--------------------------------------------------------------------------------
SAVEPOINT scenario_ordering_dependency;

\echo '\n--- SCENARIO 1: Comparing merge strategies for out-of-order source data ---'

-- Setup for Scenario 1
CREATE TABLE saga_repro.target_units_a (LIKE saga_repro.target_units_template);
CREATE TABLE saga_repro.target_units_b (LIKE saga_repro.target_units_template);
CREATE TABLE saga_repro.target_units_c (LIKE saga_repro.target_units_template);

ALTER TABLE saga_repro.target_units_a ADD PRIMARY KEY (unit_ident, valid_range WITHOUT OVERLAPS);
SELECT sql_saga.add_era('saga_repro.target_units_a', 'valid_range',
    valid_from_column_name => 'valid_from',
    valid_until_column_name => 'valid_until',
    valid_to_column_name => 'valid_to');
SELECT sql_saga.add_unique_key('saga_repro.target_units_a', ARRAY['unit_ident'], key_type => 'natural');
ALTER TABLE saga_repro.target_units_b ADD PRIMARY KEY (unit_ident, valid_range WITHOUT OVERLAPS);
SELECT sql_saga.add_era('saga_repro.target_units_b', 'valid_range',
    valid_from_column_name => 'valid_from',
    valid_until_column_name => 'valid_until',
    valid_to_column_name => 'valid_to');
SELECT sql_saga.add_unique_key('saga_repro.target_units_b', ARRAY['unit_ident'], key_type => 'natural');
ALTER TABLE saga_repro.target_units_c ADD PRIMARY KEY (unit_ident, valid_range WITHOUT OVERLAPS);
SELECT sql_saga.add_era('saga_repro.target_units_c', 'valid_range',
    valid_from_column_name => 'valid_from',
    valid_until_column_name => 'valid_until',
    valid_to_column_name => 'valid_to');
SELECT sql_saga.add_unique_key('saga_repro.target_units_c', ARRAY['unit_ident'], key_type => 'natural');

CREATE TABLE saga_repro.source_units_ordering (LIKE saga_repro.source_units_template INCLUDING ALL);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA saga_repro TO sql_saga_unprivileged_user;


INSERT INTO saga_repro.source_units_ordering (batch_seq, unit_ident, name, valid_from, valid_to) VALUES
    (1, 'unit1', 'Initial P1',   '2023-01-01', '2023-03-31'),
    (1, 'unit1', 'Initial P2',   '2023-04-01', '2023-06-30'),
    (1, 'unit1', 'Initial P3',   '2023-07-01', '2023-09-30'),
    (2, 'unit1', 'Replacing pA', '2023-02-15', '2023-05-15'),
    (2, 'unit1', 'Replacing pB', '2023-05-16', '2023-08-15'),
    (2, 'unit1', 'Replacing pC', '2023-08-16', '2023-12-01');
GRANT ALL ON saga_repro.source_units_ordering TO sql_saga_unprivileged_user;

SET ROLE TO sql_saga_unprivileged_user;

-- Strategy A: Process one row at a time (baseline for correctness)
\echo '\n--- STRATEGY A: Processing one row at a time ---\n'
CREATE TEMP TABLE source_a AS SELECT * FROM saga_repro.source_units_ordering;

-- Row 1
CREATE TEMP VIEW source_view_1 AS SELECT row_id, unit_ident, name, valid_from, valid_to, errors, merge_status FROM source_a WHERE row_id = 1;
CALL sql_saga.temporal_merge('saga_repro.target_units_a', 'source_view_1', natural_identity_columns => ARRAY['unit_ident'], mode => 'MERGE_ENTITY_UPSERT', update_source_with_feedback => true, feedback_status_column => 'merge_status', feedback_status_key => 'run1');
-- Row 2
CREATE TEMP VIEW source_view_2 AS SELECT row_id, unit_ident, name, valid_from, valid_to, errors, merge_status FROM source_a WHERE row_id = 2;
CALL sql_saga.temporal_merge('saga_repro.target_units_a', 'source_view_2', natural_identity_columns => ARRAY['unit_ident'], mode => 'MERGE_ENTITY_UPSERT', update_source_with_feedback => true, feedback_status_column => 'merge_status', feedback_status_key => 'run2');
-- Row 3
CREATE TEMP VIEW source_view_3 AS SELECT row_id, unit_ident, name, valid_from, valid_to, errors, merge_status FROM source_a WHERE row_id = 3;
CALL sql_saga.temporal_merge('saga_repro.target_units_a', 'source_view_3', natural_identity_columns => ARRAY['unit_ident'], mode => 'MERGE_ENTITY_UPSERT', update_source_with_feedback => true, feedback_status_column => 'merge_status', feedback_status_key => 'run3');
-- Row 4
CREATE TEMP VIEW source_view_4 AS SELECT row_id, unit_ident, name, valid_from, valid_to, errors, merge_status FROM source_a WHERE row_id = 4;
CALL sql_saga.temporal_merge('saga_repro.target_units_a', 'source_view_4', natural_identity_columns => ARRAY['unit_ident'], mode => 'MERGE_ENTITY_UPSERT', update_source_with_feedback => true, feedback_status_column => 'merge_status', feedback_status_key => 'run4');
-- Row 5
CREATE TEMP VIEW source_view_5 AS SELECT row_id, unit_ident, name, valid_from, valid_to, errors, merge_status FROM source_a WHERE row_id = 5;
CALL sql_saga.temporal_merge('saga_repro.target_units_a', 'source_view_5', natural_identity_columns => ARRAY['unit_ident'], mode => 'MERGE_ENTITY_UPSERT', update_source_with_feedback => true, feedback_status_column => 'merge_status', feedback_status_key => 'run5');
-- Row 6
CREATE TEMP VIEW source_view_6 AS SELECT row_id, unit_ident, name, valid_from, valid_to, errors, merge_status FROM source_a WHERE row_id = 6;
CALL sql_saga.temporal_merge('saga_repro.target_units_a', 'source_view_6', natural_identity_columns => ARRAY['unit_ident'], mode => 'MERGE_ENTITY_UPSERT', update_source_with_feedback => true, feedback_status_column => 'merge_status', feedback_status_key => 'run6');

-- Strategy B: Process in logical batches
CREATE TEMP TABLE source_b AS SELECT * FROM saga_repro.source_units_ordering;
CREATE TEMP VIEW source_view_b1 AS SELECT row_id, unit_ident, name, valid_from, valid_to, errors, merge_status FROM source_b WHERE batch_seq = 1;
CREATE TEMP VIEW source_view_b2 AS SELECT row_id, unit_ident, name, valid_from, valid_to, errors, merge_status FROM source_b WHERE batch_seq = 2;

\echo '\n--- STRATEGY B: Processing in logical batches ---\n'
CALL sql_saga.temporal_merge(
    'saga_repro.target_units_b', 'source_view_b1',
    natural_identity_columns => ARRAY['unit_ident'], mode => 'MERGE_ENTITY_UPSERT',
    update_source_with_feedback => true, feedback_status_column => 'merge_status', feedback_status_key => 'batch1'
);
CALL sql_saga.temporal_merge(
    'saga_repro.target_units_b', 'source_view_b2',
    natural_identity_columns => ARRAY['unit_ident'], mode => 'MERGE_ENTITY_UPSERT',
    update_source_with_feedback => true, feedback_status_column => 'merge_status', feedback_status_key => 'batch2'
);

-- Strategy C: Process all rows in one batch (the failing case)
CREATE TEMP TABLE source_c AS SELECT * FROM saga_repro.source_units_ordering;
CREATE TEMP VIEW source_view_c AS SELECT row_id, unit_ident, name, valid_from, valid_to, errors, merge_status FROM source_c;

CALL sql_saga.temporal_merge(
    'saga_repro.target_units_c', 'source_view_c',
    natural_identity_columns => ARRAY['unit_ident'], mode => 'MERGE_ENTITY_UPSERT',
    update_source_with_feedback => true, feedback_status_column => 'merge_status', feedback_status_key => 'run'
);


-- Final results for Scenario 1
\echo '\n\n--- FINAL COMPARISON OF FINAL STATES (SCENARIO 1) ---'
\echo '\n-- Strategy A: One-by-one Result'
SELECT unit_ident, name, valid_from, valid_to FROM saga_repro.target_units_a ORDER BY valid_from, name;
\echo '\n-- Strategy B: Batch-by-batch Result'
SELECT unit_ident, name, valid_from, valid_to FROM saga_repro.target_units_b ORDER BY valid_from, name;
\echo '\n-- Strategy C: All-in-one Result'
SELECT unit_ident, name, valid_from, valid_to FROM saga_repro.target_units_c ORDER BY valid_from, name;

\echo '\n-- Diff check of strategy results (should be empty)'
\echo '\n-- Diff A vs B:'
(TABLE saga_repro.target_units_a EXCEPT TABLE saga_repro.target_units_b)
UNION ALL
(TABLE saga_repro.target_units_b EXCEPT TABLE saga_repro.target_units_a);
\echo '\n-- Diff B vs C:'
(TABLE saga_repro.target_units_b EXCEPT TABLE saga_repro.target_units_c)
UNION ALL
(TABLE saga_repro.target_units_c EXCEPT TABLE saga_repro.target_units_b);

\echo '\n\n--- FINAL COMPARISON OF FEEDBACK (SCENARIO 1) ---'
\echo '\n-- Strategy A: One-by-one Feedback'
SELECT row_id, batch_seq, name, merge_status, errors FROM source_a ORDER BY row_id;
\echo '\n-- Strategy B: Batch-by-batch Feedback'
SELECT row_id, batch_seq, name, merge_status, errors FROM source_b ORDER BY row_id;
\echo '\n-- Strategy C: All-in-one Feedback'
SELECT row_id, batch_seq, name, merge_status, errors FROM source_c ORDER BY row_id;

ROLLBACK TO SAVEPOINT scenario_ordering_dependency;

--------------------------------------------------------------------------------
-- SCENARIO 2: Coalescing Regression
--
-- This test demonstrates a regression where `temporal_merge` fails to coalesce
-- adjacent, identical time segments when they are processed in separate batches.
--------------------------------------------------------------------------------
SAVEPOINT scenario_coalescing;
\echo '\n--- SCENARIO 2: Coalescing identical, adjacent records across batches ---'

-- Setup for Scenario 2
CREATE TABLE saga_repro.target_units_coalesce (
    LIKE saga_repro.target_units_template,
    notes text -- Add a nullable column that does not exist in the source table
);
ALTER TABLE saga_repro.target_units_coalesce ADD PRIMARY KEY (unit_ident, valid_range WITHOUT OVERLAPS);
CREATE TABLE saga_repro.source_units_coalesce (LIKE saga_repro.source_units_template INCLUDING ALL);
SELECT sql_saga.add_era('saga_repro.target_units_coalesce', 'valid_range',
    valid_from_column_name => 'valid_from',
    valid_until_column_name => 'valid_until',
    valid_to_column_name => 'valid_to');
SELECT sql_saga.add_unique_key('saga_repro.target_units_coalesce', ARRAY['unit_ident'], key_type => 'natural');
GRANT ALL ON saga_repro.target_units_coalesce TO sql_saga_unprivileged_user;
GRANT ALL ON saga_repro.source_units_coalesce TO sql_saga_unprivileged_user;

-- Batch 1
INSERT INTO saga_repro.source_units_coalesce (unit_ident, name, valid_from, valid_to) VALUES
    ('unit1', 'Unit A', '2023-01-01', '2023-06-30');
SET ROLE TO sql_saga_unprivileged_user;
CALL sql_saga.temporal_merge('saga_repro.target_units_coalesce', 'saga_repro.source_units_coalesce', natural_identity_columns => ARRAY['unit_ident'], mode => 'MERGE_ENTITY_PATCH');
RESET ROLE;

\echo '\n--- State after Batch 1 ---'
SELECT unit_ident, name, valid_from, valid_to, notes FROM saga_repro.target_units_coalesce;

-- Batch 2 (the failing step)
TRUNCATE saga_repro.source_units_coalesce;
INSERT INTO saga_repro.source_units_coalesce (unit_ident, name, valid_from, valid_to) VALUES
    ('unit1', 'Unit A', '2023-07-01', '2023-12-31');

SET ROLE TO sql_saga_unprivileged_user;
CALL sql_saga.temporal_merge('saga_repro.target_units_coalesce', 'saga_repro.source_units_coalesce', natural_identity_columns => ARRAY['unit_ident'], mode => 'MERGE_ENTITY_PATCH');
RESET ROLE;

-- Final results for Scenario 2
\echo '\n-- Coalescing Test Final State (Bug Repro: 2 rows, Correct: 1 row)'
SELECT unit_ident, name, valid_from, valid_to, notes FROM saga_repro.target_units_coalesce ORDER BY valid_from;

ROLLBACK TO SAVEPOINT scenario_coalescing;


--------------------------------------------------------------------------------
-- SCENARIO 3: Ephemeral column handling in PATCH, UPSERT, and REPLACE modes
--
-- This scenario clarifies the semantic differences between the main merge modes
-- with respect to NULLs and ephemeral columns.
--------------------------------------------------------------------------------
SAVEPOINT scenario_ephemeral_modes;
\echo '\n--- SCENARIO 3: Ephemeral column handling in PATCH, UPSERT, and REPLACE modes ---'

CREATE TABLE saga_repro.target_units_ephemeral (
    id int GENERATED BY DEFAULT AS IDENTITY,
    unit_ident text NOT NULL,
    name text NOT NULL,
    -- Semantic naming for DEFAULT behavior testing:
    status_with_default text NOT NULL DEFAULT 'pending',                    -- NULL source → uses DEFAULT 'pending'
    priority_with_default int NOT NULL DEFAULT 1,                           -- NULL source → uses DEFAULT 1  
    created_at_with_default timestamptz NOT NULL DEFAULT '2025-01-01 10:00:00+00', -- NULL source → uses DEFAULT timestamp
    notes_nullable text,                                                     -- NULL source → NULL (no constraint)
    -- Audit columns (ephemeral, no defaults - must be provided):
    edit_at_no_default timestamptz NOT NULL,                               -- NULL source → constraint violation
    edit_by_user_id_no_default text NOT NULL,                              -- NULL source → constraint violation
    edit_comment_nullable text,                                             -- NULL source → NULL (no constraint)
    valid_range daterange NOT NULL,
    valid_from date NOT NULL,
    valid_to date,
    valid_until date
);
CREATE TABLE saga_repro.source_units_ephemeral (
    row_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_ident text, name text, 
    status_with_default text, priority_with_default int, created_at_with_default timestamptz,
    notes_nullable text,
    edit_at_no_default timestamptz, edit_by_user_id_no_default text, edit_comment_nullable text,
    valid_from date, valid_to date
);
ALTER TABLE saga_repro.target_units_ephemeral ADD PRIMARY KEY (id, valid_range WITHOUT OVERLAPS);
SELECT sql_saga.add_era('saga_repro.target_units_ephemeral', 'valid_range',
    valid_from_column_name => 'valid_from',
    valid_until_column_name => 'valid_until',
    valid_to_column_name => 'valid_to');
SELECT sql_saga.add_unique_key('saga_repro.target_units_ephemeral', ARRAY['id'], key_type => 'primary');
SELECT sql_saga.add_unique_key('saga_repro.target_units_ephemeral', ARRAY['unit_ident'], key_type => 'natural');
GRANT ALL ON saga_repro.target_units_ephemeral TO sql_saga_unprivileged_user;
GRANT ALL ON saga_repro.source_units_ephemeral TO sql_saga_unprivileged_user;

\echo '\n-- Case 3a: MERGE_ENTITY_PATCH'
\echo '-- Expectation: NULL for `edit_comment_nullable` is ignored (PATCH mode). DEFAULT columns and audit fields are preserved.'
SAVEPOINT case_patch;
-- Initial state for this case
TRUNCATE saga_repro.target_units_ephemeral, saga_repro.source_units_ephemeral RESTART IDENTITY;
INSERT INTO saga_repro.target_units_ephemeral (unit_ident, name, notes_nullable, valid_from, valid_to, edit_at_no_default, edit_by_user_id_no_default, edit_comment_nullable)
VALUES ('unit1', 'Unit A', 'Original notes', '2023-01-01', '2023-12-31', '2025-01-01 09:00:00+00', 'admin', 'Initial version');
INSERT INTO saga_repro.source_units_ephemeral (unit_ident, name, valid_from, valid_to, edit_at_no_default, edit_by_user_id_no_default, edit_comment_nullable)
VALUES ('unit1', 'Unit A Updated', '2023-06-01', '2023-08-31', '2025-02-01 10:30:00+00', 'user123', NULL); -- `edit_comment_nullable` is NULL, other fields provided
\echo '\n--- Initial State ---'
TABLE saga_repro.target_units_ephemeral;
\echo '\n--- Source Data ---'
TABLE saga_repro.source_units_ephemeral;

SET ROLE TO sql_saga_unprivileged_user;
CALL sql_saga.temporal_merge(
    'saga_repro.target_units_ephemeral', 'saga_repro.source_units_ephemeral',
    natural_identity_columns => ARRAY['unit_ident'],
    ephemeral_columns => ARRAY['edit_at_no_default', 'edit_by_user_id_no_default', 'edit_comment_nullable'],
    mode => 'MERGE_ENTITY_PATCH'
);
RESET ROLE;
\echo '\n--- Final State (PATCH) ---'
SELECT unit_ident, name, notes_nullable, valid_from, valid_to, edit_comment_nullable FROM saga_repro.target_units_ephemeral ORDER BY valid_from;
ROLLBACK TO SAVEPOINT case_patch;


\echo '\n-- Case 3b: MERGE_ENTITY_UPSERT'
\echo '-- Expectation: NULL DEFAULT columns use table defaults. NULL audit fields cause constraint violation.'
SAVEPOINT case_upsert;
-- Initial state for this case  
TRUNCATE saga_repro.target_units_ephemeral, saga_repro.source_units_ephemeral RESTART IDENTITY;
INSERT INTO saga_repro.target_units_ephemeral (unit_ident, name, notes_nullable, valid_from, valid_to, edit_at_no_default, edit_by_user_id_no_default, edit_comment_nullable)
VALUES ('unit1', 'Unit A', 'Original notes', '2023-01-01', '2023-12-31', '2025-01-01 09:00:00+00', 'admin', 'Initial version');
-- Source with NULL values for DEFAULT columns (should use defaults) and NULL audit fields (should cause error)
INSERT INTO saga_repro.source_units_ephemeral (unit_ident, name, status_with_default, priority_with_default, valid_from, valid_to, edit_at_no_default, edit_by_user_id_no_default, edit_comment_nullable)
VALUES ('unit1', 'Unit A Updated', NULL, NULL, '2023-06-01', '2023-08-31', NULL, NULL, NULL);
\echo '\n--- Initial State ---'
TABLE saga_repro.target_units_ephemeral;
\echo '\n--- Source Data ---'
TABLE saga_repro.source_units_ephemeral;

SET ROLE TO sql_saga_unprivileged_user;
CALL sql_saga.temporal_merge(
    'saga_repro.target_units_ephemeral', 'saga_repro.source_units_ephemeral',
    natural_identity_columns => ARRAY['unit_ident'],
    ephemeral_columns => ARRAY['edit_at_no_default', 'edit_by_user_id_no_default', 'edit_comment_nullable'],
    mode => 'MERGE_ENTITY_UPSERT'
);
RESET ROLE;
\echo '\n--- Final State (UPSERT) ---'
SELECT unit_ident, name, notes_nullable, valid_from, valid_to, edit_comment_nullable FROM saga_repro.target_units_ephemeral ORDER BY valid_from;
ROLLBACK TO SAVEPOINT case_upsert;


\echo '\n-- Case 3c: MERGE_ENTITY_REPLACE'
\echo '-- Expectation: Source completely replaces target. NULL DEFAULT columns use table defaults. NULL audit fields cause constraint violation.'
SAVEPOINT case_replace;
-- Initial state for this case
TRUNCATE saga_repro.target_units_ephemeral, saga_repro.source_units_ephemeral RESTART IDENTITY;
INSERT INTO saga_repro.target_units_ephemeral (unit_ident, name, notes_nullable, valid_from, valid_to, edit_at_no_default, edit_by_user_id_no_default, edit_comment_nullable)
VALUES ('unit1', 'Unit A', 'Original notes', '2023-01-01', '2023-12-31', '2025-01-01 09:00:00+00', 'admin', 'Initial version');
-- Source with NULL values for DEFAULT columns (should use defaults) and NULL audit fields (should cause error)  
INSERT INTO saga_repro.source_units_ephemeral (unit_ident, name, status_with_default, priority_with_default, valid_from, valid_to, edit_at_no_default, edit_by_user_id_no_default, edit_comment_nullable)
VALUES ('unit1', 'Unit A Updated', NULL, NULL, '2023-06-01', '2023-08-31', NULL, NULL, NULL);
\echo '\n--- Initial State ---'
TABLE saga_repro.target_units_ephemeral;
\echo '\n--- Source Data ---'
TABLE saga_repro.source_units_ephemeral;

SET ROLE TO sql_saga_unprivileged_user;
CALL sql_saga.temporal_merge(
    'saga_repro.target_units_ephemeral', 'saga_repro.source_units_ephemeral',
    natural_identity_columns => ARRAY['unit_ident'],
    ephemeral_columns => ARRAY['edit_at_no_default', 'edit_by_user_id_no_default', 'edit_comment_nullable'],
    mode => 'MERGE_ENTITY_REPLACE'
);
RESET ROLE;
\echo '\n--- Final State (REPLACE) ---'
SELECT unit_ident, name, notes_nullable, valid_from, valid_to, edit_comment_nullable FROM saga_repro.target_units_ephemeral ORDER BY valid_from;
ROLLBACK TO SAVEPOINT case_replace;


ROLLBACK TO SAVEPOINT scenario_ephemeral_modes;


--------------------------------------------------------------------------------
-- SCENARIO 4: UPSERT mode with NOT NULL DEFAULT columns
--
-- This test validates that when using MERGE_ENTITY_UPSERT, an incoming NULL
-- for a column that is defined as NOT NULL DEFAULT does not cause a NOT NULL
-- violation. Instead, the executor preserves the existing value, effectively
-- treating NULL as "no change" for this specific combination of constraints and mode.
--------------------------------------------------------------------------------
SAVEPOINT scenario_not_null_default;
\echo '\n--- SCENARIO 4: UPSERT with NOT NULL DEFAULT columns ---'

CREATE TABLE saga_repro.target_not_null_default (
    unit_ident text NOT NULL,
    name text NOT NULL,
    status text NOT NULL DEFAULT 'active',
    valid_range daterange NOT NULL,
    valid_from date NOT NULL,
    valid_to date,
    valid_until date
);
CREATE TABLE saga_repro.source_not_null_default (
    row_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_ident text, name text, status text,
    valid_from date, valid_to date
);

ALTER TABLE saga_repro.target_not_null_default ADD PRIMARY KEY (unit_ident, valid_range WITHOUT OVERLAPS);
SELECT sql_saga.add_era('saga_repro.target_not_null_default', 'valid_range',
    valid_from_column_name => 'valid_from',
    valid_until_column_name => 'valid_until',
    valid_to_column_name => 'valid_to');
SELECT sql_saga.add_unique_key('saga_repro.target_not_null_default', ARRAY['unit_ident'], key_type => 'natural');
GRANT ALL ON saga_repro.target_not_null_default TO sql_saga_unprivileged_user;
GRANT ALL ON saga_repro.source_not_null_default TO sql_saga_unprivileged_user;

-- Initial state: one record with default status
INSERT INTO saga_repro.target_not_null_default (unit_ident, name, valid_from, valid_until)
VALUES ('unit1', 'Unit A', '2023-01-01', '2024-01-01');

\echo '\n--- Initial State ---'
TABLE saga_repro.target_not_null_default;

-- Source data: provides NULL for the 'status' column, which has a NOT NULL DEFAULT constraint.
INSERT INTO saga_repro.source_not_null_default (unit_ident, name, status, valid_from, valid_to)
VALUES ('unit1', 'Unit A Updated', NULL, '2023-06-01', '2023-08-31');

\echo '\n--- Source Data ---'
TABLE saga_repro.source_not_null_default;

SET ROLE TO sql_saga_unprivileged_user;
CALL sql_saga.temporal_merge(
    'saga_repro.target_not_null_default', 'saga_repro.source_not_null_default',
    natural_identity_columns => ARRAY['unit_ident'],
    mode => 'MERGE_ENTITY_UPSERT'
);
RESET ROLE;

\echo '\n--- Final State (UPSERT with NOT NULL DEFAULT) ---'
\echo '-- Expectation: The `status` remains "active" in all segments, as the incoming NULL was ignored.'
SELECT unit_ident, name, status, valid_from, valid_to FROM saga_repro.target_not_null_default ORDER BY valid_from;

ROLLBACK TO SAVEPOINT scenario_not_null_default;

--------------------------------------------------------------------------------
-- SCENARIO 5: UPDATE_FOR_PORTION_OF incorrectly merges distinct attribute values
--
-- This reproduces a critical Statbus regression where updating a non-name attribute
-- (like legal_form_id) via a FOR_PORTION_OF view incorrectly merges temporal rows
-- that have different names, losing historical name changes.
--
-- Issue: When the same entity has different attribute values across adjacent time
-- periods (e.g., name changed from "A" to "B"), updating another attribute across
-- the full timeline should preserve both distinct names, not merge them into one.
--------------------------------------------------------------------------------
SAVEPOINT scenario_update_for_portion_of_merging;

\echo '\n--- SCENARIO 5: UPDATE_FOR_PORTION_OF should preserve distinct attribute values ---'

-- Create tables mimicking Statbus legal_unit structure (simplified)
CREATE TABLE saga_repro.legal_unit (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    legal_form_id int NOT NULL DEFAULT 1,
    valid_range daterange NOT NULL,
    valid_from date NOT NULL,
    valid_until date
);

SELECT sql_saga.add_era('saga_repro.legal_unit', 'valid_range',
    valid_from_column_name => 'valid_from',
    valid_until_column_name => 'valid_until');
ALTER TABLE saga_repro.legal_unit ADD PRIMARY KEY (id, valid_range WITHOUT OVERLAPS);
SELECT sql_saga.add_unique_key('saga_repro.legal_unit', ARRAY['id'], key_type => 'primary');

-- Create FOR_PORTION_OF view
SELECT sql_saga.add_for_portion_of_view('saga_repro.legal_unit', era_name => 'valid');

GRANT ALL ON saga_repro.legal_unit TO sql_saga_unprivileged_user;
GRANT ALL ON saga_repro.legal_unit__for_portion_of_valid TO sql_saga_unprivileged_user;

-- Insert test data matching Statbus pattern:
-- Same entity ID, different names, adjacent time periods
INSERT INTO saga_repro.legal_unit (id, name, legal_form_id, valid_from, valid_until) VALUES
    (1, 'EQUATOR GLOBE SOLUTIONS', 1, '2023-01-01', '2024-01-01'),
    (1, 'EQUATOR GLOBE SOLUTIONS #2', 1, '2024-01-01', '2026-01-01');

\echo '\n--- Initial State: Two rows, same ID, different names ---'
SELECT id, name, legal_form_id, valid_from, valid_until 
FROM saga_repro.legal_unit 
ORDER BY valid_from;

-- Execute the problematic UPDATE via FOR_PORTION_OF view
-- This should update legal_form_id across the FULL timeline (2023-2026)
-- Expected: 2 rows with legal_form_id=2, preserving both distinct names
-- Bug: 1 merged row losing the original name "EQUATOR GLOBE SOLUTIONS"
SET ROLE TO sql_saga_unprivileged_user;
UPDATE saga_repro.legal_unit__for_portion_of_valid
SET legal_form_id = 2, valid_from = '2023-01-01', valid_until = '2026-01-01'
WHERE id = 1;
RESET ROLE;

\echo '\n--- After UPDATE FOR PORTION OF (full timeline) ---'
\echo '-- Expected: 2 rows preserving distinct names'
\echo '-- Bug: 1 row with merged name (loses "EQUATOR GLOBE SOLUTIONS")'
SELECT id, name, legal_form_id, valid_from, valid_until 
FROM saga_repro.legal_unit 
ORDER BY valid_from;

ROLLBACK TO SAVEPOINT scenario_update_for_portion_of_merging;


--------------------------------------------------------------------------------
-- SCENARIO 6: Timeline splits should preserve audit columns (edit_at, edit_by_user_id)
--
-- Issue: When temporal_merge splits a timeline segment (e.g., a PATCH_FOR_PORTION_OF
-- operation that affects the middle of an existing timeline), the audit columns
-- (edit_at, edit_by_user_id, edit_comment) should be preserved from the original
-- segment, not reset to NULL or now().
--
-- Currently: The split segments lose their audit trail, with edit_at being reset
-- to the current timestamp and edit_by_user_id potentially being nulled.
--------------------------------------------------------------------------------
SAVEPOINT scenario_audit_column_preservation;

\echo '\n--- SCENARIO 6: Timeline splits should preserve audit columns ---'

-- Create a temporal table with semantic audit columns  
CREATE TABLE saga_repro.audited_unit (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    status text NOT NULL,
    valid_range daterange NOT NULL,
    valid_from date NOT NULL,
    valid_until date,
    -- Audit columns with fixed defaults for deterministic testing - semantic naming shows expected DEFAULT behavior
    edit_at_with_default timestamptz NOT NULL DEFAULT '2024-01-01 02:00:00-08'::timestamptz,  -- NULL source → uses this DEFAULT
    edit_by_user_id_with_default int NOT NULL DEFAULT 1,                                      -- NULL source → uses this DEFAULT
    edit_comment_nullable text                                                                -- NULL source → NULL (no constraint)
);

SELECT sql_saga.add_era('saga_repro.audited_unit', 'valid_range',
    valid_from_column_name => 'valid_from',
    valid_until_column_name => 'valid_until');
ALTER TABLE saga_repro.audited_unit ADD PRIMARY KEY (id, valid_range WITHOUT OVERLAPS);
SELECT sql_saga.add_unique_key('saga_repro.audited_unit', ARRAY['id'], key_type => 'primary');

-- Insert initial data: one row spanning the full year 2024 with specific audit info
INSERT INTO saga_repro.audited_unit (id, name, status, valid_from, valid_until, edit_at_with_default, edit_by_user_id_with_default, edit_comment_nullable)
VALUES (1, 'Unit Alpha', 'active', '2024-01-01', '2025-01-01', '2024-01-15 06:30:00-08', 100, 'Initial creation');

\echo '\n--- Initial State: One row spanning full year 2024 ---'
SELECT id, name, status, valid_from, valid_until, edit_at_with_default, edit_by_user_id_with_default, edit_comment_nullable
FROM saga_repro.audited_unit
ORDER BY valid_from;

-- Create a source table to update just the middle portion (April-September)
-- This should cause a 3-way split of the timeline
CREATE TEMP TABLE source_audit_split (
    row_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id int,
    status text,
    valid_from date,
    valid_until date,
    edit_at_with_default timestamptz,
    edit_by_user_id_with_default int,
    edit_comment_nullable text
);

INSERT INTO source_audit_split (id, status, valid_from, valid_until, edit_at_with_default, edit_by_user_id_with_default, edit_comment_nullable)
VALUES (1, 'suspended', '2024-04-01', '2024-10-01', '2024-04-05 09:45:00-07', 200, 'Status update for Q2-Q3');

\echo '\n--- Source: Update middle portion (April-September) with new audit info ---'
SELECT id, status, valid_from, valid_until, edit_at_with_default, edit_by_user_id_with_default, edit_comment_nullable
FROM source_audit_split;

-- Perform the merge which will split the timeline
CALL sql_saga.temporal_merge(
    'saga_repro.audited_unit', 'source_audit_split',
    primary_identity_columns => ARRAY['id'],
    ephemeral_columns => ARRAY['edit_at_with_default', 'edit_by_user_id_with_default', 'edit_comment_nullable'],
    mode => 'MERGE_ENTITY_PATCH'
);

\echo '\n--- After Timeline Split ---'
\echo '-- Expected: 3 segments with preserved audit trail'
\echo '--   Jan-Mar:  status=active,    edit_at_with_default=2024-01-15 06:30:00-08, edit_by_user_id_with_default=100 (PRESERVED from original)'
\echo '--   Apr-Sep:  status=suspended, edit_at_with_default=2024-04-05 09:45:00-07, edit_by_user_id_with_default=200 (NEW from source)'
\echo '--   Oct-Dec:  status=active,    edit_at_with_default=2024-01-15 06:30:00-08, edit_by_user_id_with_default=100 (PRESERVED from original)'
\echo '--'
\echo '-- Test verifies: Timeline splits preserve audit trail - edge segments keep original values, middle segment uses source values'
SELECT id, name, status, valid_from, valid_until, 
       edit_at_with_default, edit_by_user_id_with_default, edit_comment_nullable
FROM saga_repro.audited_unit
ORDER BY valid_from;

ROLLBACK TO SAVEPOINT scenario_audit_column_preservation;

--------------------------------------------------------------------------------
-- SCENARIO 7: Ephemeral column with NOT NULL DEFAULT missing from source
--
-- This reproduces a regression where an ephemeral column declared in the
-- temporal_merge call but MISSING from the source view causes a NOT NULL
-- violation instead of using the column's DEFAULT value.
--
-- Use case: Audit columns like `created_at` should use their DEFAULT when
-- inserting new records, even when declared as ephemeral for timeline splits.
--------------------------------------------------------------------------------
SAVEPOINT scenario_ephemeral_missing_from_source;

\echo '\n--- SCENARIO 7: Ephemeral column with NOT NULL DEFAULT missing from source ---'

CREATE TABLE saga_repro.target_with_audit (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    key_col TEXT NOT NULL,
    data_col TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT statement_timestamp(),
    valid_from DATE NOT NULL DEFAULT CURRENT_DATE,
    valid_until DATE NOT NULL DEFAULT 'infinity'::date,
    valid_range daterange NOT NULL,
    PRIMARY KEY (id, valid_range WITHOUT OVERLAPS)
);

SELECT sql_saga.add_era('saga_repro.target_with_audit', 'valid_range',
    valid_from_column_name => 'valid_from',
    valid_until_column_name => 'valid_until');
SELECT sql_saga.add_unique_key('saga_repro.target_with_audit', ARRAY['key_col'], key_type => 'natural');

-- Source table intentionally OMITS created_at - should use DEFAULT
CREATE TABLE saga_repro.source_without_audit (
    row_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_col TEXT NOT NULL,
    data_col TEXT,
    valid_from DATE NOT NULL DEFAULT CURRENT_DATE,
    valid_until DATE NOT NULL DEFAULT 'infinity'::date
);

INSERT INTO saga_repro.source_without_audit (key_col, data_col) VALUES ('test_key', 'test_data');

GRANT ALL ON saga_repro.target_with_audit TO sql_saga_unprivileged_user;
GRANT ALL ON saga_repro.source_without_audit TO sql_saga_unprivileged_user;

CREATE VIEW saga_repro.source_without_audit_view AS
SELECT row_id, key_col, data_col, valid_from, valid_until
FROM saga_repro.source_without_audit;

GRANT SELECT ON saga_repro.source_without_audit_view TO sql_saga_unprivileged_user;

\echo '\n--- Source view (note: no created_at column) ---'
\d saga_repro.source_without_audit_view

SET ROLE TO sql_saga_unprivileged_user;

-- This should succeed - created_at should use its DEFAULT value
CALL sql_saga.temporal_merge(
    target_table => 'saga_repro.target_with_audit'::regclass,
    source_table => 'saga_repro.source_without_audit_view'::regclass,
    primary_identity_columns => ARRAY['id'],
    natural_identity_columns => ARRAY['key_col'],
    mode => 'MERGE_ENTITY_REPLACE'::sql_saga.temporal_merge_mode,
    ephemeral_columns => ARRAY['created_at']
);

RESET ROLE;

\echo '\n--- Result: created_at should have DEFAULT value (not NULL) ---'
SELECT id, key_col, data_col, created_at IS NOT NULL as has_created_at, valid_from, valid_until
FROM saga_repro.target_with_audit;

ROLLBACK TO SAVEPOINT scenario_ephemeral_missing_from_source;


--------------------------------------------------------------------------------
-- SCENARIO 8: Timeline split must preserve history for defaulted columns
--
-- This reproduces a regression where timeline splits (e.g., from an update in the
-- middle of a validity range) caused columns with DEFAULT values to revert to their
-- default, instead of preserving the historical value from the original row.
--
-- Case:
-- 1. Target row has `business_col = 'PRESERVED'` (Default is 'DEFAULT').
-- 2. Source updates `other_col` for a sub-range (e.g., Apr-Dec).
-- 3. The timeline splits. The new segment must keep `business_col = 'PRESERVED'`.
--------------------------------------------------------------------------------
SAVEPOINT scenario_default_column_preservation;

\echo '\n--- SCENARIO 8: Timeline split must preserve history for defaulted columns ---'

CREATE TABLE saga_repro.target_default_preservation (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    business_col text NOT NULL DEFAULT 'default_value', 
    other_col text,
    valid_range daterange NOT NULL,
    valid_from date NOT NULL,
    valid_until date,
    PRIMARY KEY (id, valid_range WITHOUT OVERLAPS)
);

SELECT sql_saga.add_era('saga_repro.target_default_preservation', 'valid_range', 
    valid_from_column_name => 'valid_from', 
    valid_until_column_name => 'valid_until');
SELECT sql_saga.add_unique_key('saga_repro.target_default_preservation', ARRAY['name'], key_type => 'natural');

GRANT ALL ON saga_repro.target_default_preservation TO sql_saga_unprivileged_user;

-- Insert initial data (Period 1)
INSERT INTO saga_repro.target_default_preservation (name, business_col, other_col, valid_from, valid_until)
VALUES ('TestEntity', 'PRESERVED_VALUE', 'old_val', '2023-01-01', '2024-01-01');

\echo '\n--- Initial State: One row with non-default value ---'
SELECT name, business_col, other_col, valid_from, valid_until FROM saga_repro.target_default_preservation;

CREATE TABLE saga_repro.source_default_preservation (
    row_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    other_col text,
    valid_from date,
    valid_until date
);

-- Update 'other_col' in the middle of the range
INSERT INTO saga_repro.source_default_preservation (name, other_col, valid_from, valid_until)
VALUES ('TestEntity', 'new_val', '2023-06-01', '2024-01-01');

GRANT ALL ON saga_repro.source_default_preservation TO sql_saga_unprivileged_user;

CREATE VIEW saga_repro.source_default_preservation_view AS 
SELECT row_id, name, other_col, valid_from, valid_until FROM saga_repro.source_default_preservation;

GRANT SELECT ON saga_repro.source_default_preservation_view TO sql_saga_unprivileged_user;

SET ROLE TO sql_saga_unprivileged_user;

-- Execute merge
-- 'business_col' is MISSING from source.
-- We verify that the split segment preserves 'PRESERVED_VALUE'.
CALL sql_saga.temporal_merge(
    'saga_repro.target_default_preservation', 
    'saga_repro.source_default_preservation_view', 
    natural_identity_columns => ARRAY['name'],
    mode => 'MERGE_ENTITY_PATCH'
);

RESET ROLE;

\echo '\n--- Final State: Split timeline, value preserved in new segment ---'
SELECT name, business_col, other_col, valid_from, valid_until 
FROM saga_repro.target_default_preservation 
ORDER BY valid_from;

ROLLBACK TO SAVEPOINT scenario_default_column_preservation;


ROLLBACK;

\i sql/include/test_teardown.sql
